### ISSUE TITLE
ThorVG Player shows empty canvas for a while when it becomes intersecting state

### ISSUE THREAD

**Issue by hermet** [thorvg/thorvg.web#34]
Please check the issue, currently ThorVG Player seems having same problem.

https://github.com/LottieFiles/dotlottie-web/issues/273

**Comment by tinyjin** [comment]
In ThorVG Web Player, the IntersectionObserver is default. This means current ThorVG Viewer has same condition to reproduce.

However in the viewer, I see it renders well.


![CleanShot 2024-07-05 at 15 08 18@2x](https://github.com/thorvg/thorvg.web/assets/11167117/58c2968d-00c3-459e-bbfc-0a72c98da351)

Additionally, we don't have debouncing logic in that observer. The issue dotLottie has comes from JavaScript side not WASM.
Observer callback seems to have some delays, and gets wrong event order due to the debounce.

ThorVG Web doesn't have it, so I think this is fine here. If you have similar error, could you please share your case?

**Comment by hermet** [comment]
Can't reproduce it with the latest version.
