### ISSUE TITLE
perf-test: ensure high animation quality across all players

### ISSUE THREAD

**Issue by theashraf** [thorvg/thorvg.web#8]
I've noticed that only lottie-web renders animations with the best quality, while thorvg and dotLottie-web animations are a bit blurry.

lottie-web
<img width="774" alt="image" src="https://github.com/thorvg/thorvg.web/assets/39750790/b7a4fd05-54fc-4dcb-8b85-c592d140c2df">

dotLottie-web & thorvg
<img width="691" alt="Screenshot 2024-05-22 at 4 37 02 AM" src="https://github.com/thorvg/thorvg.web/assets/39750790/9052f6a4-e4fb-4835-9424-544fe20ccf87">

[Suggestion]
We can remove the hardcoded dotLottie web renderConfig devicePixelRatio and ensure that the thorvg canvas is resized for the best quality based on the devicePixelRatio, as it's implemented in dotLottie-web.

**Comment by hermet** [comment]
Hmm... This is the captured image from my testing device. I can't determine whether Lottie-web is better than the others like your captured image. The only noticeable difference might be the edge quality due to the different anti-aliasing mechanisms.

[left: thorvg,   center: dotlottie,   right: lottie-web]
![image](https://github.com/thorvg/thorvg.web/assets/3711518/5878dd46-8615-4455-a91f-e3565d476cec)


[thorvg]
![image](https://github.com/thorvg/thorvg.web/assets/3711518/9c764c09-87ed-4174-8122-f35f37cf7a4a)

[dotlottie]
![image](https://github.com/thorvg/thorvg.web/assets/3711518/7abb5e3e-0755-4b26-97a1-f04db743298f)

[lottie-web]
![image](https://github.com/thorvg/thorvg.web/assets/3711518/be8b586d-14c3-4c0e-9c4c-dd66c54a9521)

**Comment by hermet** [comment]
The truly important part is whether all three players output images at the same resolution. If one side outputs at a higher resolution, it can significantly affect performance measurement, so it is important to ensure they are the same.

Here are 2 additional observations from my chrome browser:
1. When scaled up the browser, lottie-web resolution is scaled up as well. Obviously, lottie-web considers a certain scale factor.
2. When applied the devicePixelRatio to the dotlottie player, its quality looks better than lottie-web in default scale factor (100%).

**Comment by hermet** [comment]
More Test factors.
- DRP doesn't work with lottie-web while canvas-render works with it on a test machine. We need to clarify this with multiple systems(devices) other than Mac.
